[package]
name = "osc-cost"
version = "0.1.0"
edition = "2021"
authors = ["OpenSource Team <opensource@outscale.com>"]
license = "BSD-3-Clause"
description = "osc-cost helps measuring Outscale infrastructure costs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
http = "0.1.21"
outscale_api = { version = "1.2.0", features = ["rustls-tls"], default-features = false }
rand = "0.8.5"